version: 2
jobs:
    build:
        docker:
            - image: circleci/java:8-jdk
        steps:
            - checkout
            - run:
                name: Maven Install & Deploy
                command: mvn test
 workflows:
    version: 2
    build_test_deploy:
        jobs:
            - build